import sys
import os

if len(sys.argv) != 4:
    print("Usage: python embed_binary.py <input_file> <var_name> <output_header>")
    sys.exit(1)

input_file = sys.argv[1]
var_name = sys.argv[2]
output_header = sys.argv[3]

data = b''
if os.path.exists(input_file):
    with open(input_file, 'rb') as f:
        data = f.read()
else:
    print(f"Warning: {input_file} not found, generating empty vector.")

out = []
out.append("#pragma once\n")
out.append("#include <vector>\n")
out.append("#include <cstdint>\n\n")
out.append(f"// Auto-generated by cmake/embed_binary.py\n")
out.append(f"static const std::vector<uint8_t> {var_name} = {{\n")

chunk_size = 16
for i in range(0, len(data), chunk_size):
    chunk = data[i:i+chunk_size]
    hex_str = ", ".join([f"0x{b:02x}" for b in chunk])
    out.append(f"    {hex_str},\n")

out.append("};\n")

with open(output_header, 'w') as f:
    f.writelines(out)

print(f"Generated {output_header} with {len(data)} bytes.")
