# cmake/EmbedCRTShaders.cmake
# Called by add_custom_command to embed crt.vert and crt.frag into a C++ header.
# Usage:
#   cmake -DVERT_FILE=... -DFRAG_FILE=... -DOUTPUT=... -P EmbedCRTShaders.cmake

cmake_minimum_required(VERSION 3.14)

file(READ "${VERT_FILE}" VERT_CONTENT)
file(READ "${FRAG_FILE}" FRAG_CONTENT)

file(WRITE "${OUTPUT}"
"#pragma once

// Auto-generated by cmake/EmbedCRTShaders.cmake — do NOT edit manually.
// Edit Frontend/GUI/Video/crt.vert and crt.frag instead.

static const char* kCRTVertSrc = R\"glsl(
${VERT_CONTENT}
)glsl\";

static const char* kCRTFragSrc = R\"glsl(
${FRAG_CONTENT}
)glsl\";
")
