import sys
import os

if len(sys.argv) != 5:
    print("Usage: python EmbedCC65.py <cc65_snapshot_dir> <linker_dir> <libs_dir> <out_header>")
    sys.exit(1)

snapshot_dir = sys.argv[1]
linker_dir = sys.argv[2]
libs_dir = sys.argv[3]
out_header = sys.argv[4]

embed_dirs = {
    os.path.join(snapshot_dir, "include"): "include",
    os.path.join(snapshot_dir, "asminc"): "asminc",
    linker_dir: "Linker",
    libs_dir: "include/Libs"
}

embed_files = {
    os.path.join(snapshot_dir, "lib", "none.lib"): "lib/none.lib"
}

files_to_process = []

for physical_dir, virtual_prefix in embed_dirs.items():
    if not os.path.exists(physical_dir):
        print(f"Warning: directory {physical_dir} not found")
        continue
    for root, _, files in os.walk(physical_dir):
        for f in files:
            full_path = os.path.join(root, f)
            rel_path = os.path.relpath(full_path, physical_dir)
            virtual_path = f"{virtual_prefix}/{rel_path}".replace('\\', '/')
            files_to_process.append((full_path, virtual_path))

for physical_file, virtual_path in embed_files.items():
    if not os.path.exists(physical_file):
        print(f"Warning: file {physical_file} not found")
        continue
    files_to_process.append((physical_file, virtual_path))

out = []
out.append("#pragma once\n")
out.append("#include <vector>\n")
out.append("#include <string>\n")
out.append("#include <map>\n")
out.append("#include <cstdint>\n\n")
out.append("// Auto-generated by cmake/EmbedCC65.py\n")

out.append("static const std::map<std::string, std::vector<uint8_t>> embedded_cc65_files = {\n")

for full_path, vpath in files_to_process:
    with open(full_path, 'rb') as f:
        data = f.read()
    
    out.append(f"  {{\"{vpath}\", {{\n")
    
    chunk_size = 32
    for i in range(0, len(data), chunk_size):
        chunk = data[i:i+chunk_size]
        hex_str = ", ".join([f"0x{b:02x}" for b in chunk])
        out.append(f"    {hex_str},\n")
    
    out.append("  }}\n")
    out.append(",\n") # comma between map items

out.append("};\n")

with open(out_header, 'w') as f:
    f.writelines(out)

print(f"Generated {out_header} with {len(files_to_process)} embedded files.")
